// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGKGZBuPl1yyBmuERlKJq5dGTKbof-FO8',
    appId: '1:1099117948271:web:8c934e94e2a12a115bcc9a',
    messagingSenderId: '1099117948271',
    projectId: 'construction-store-mobile-app',
    authDomain: 'construction-store-mobile-app.firebaseapp.com',
    storageBucket: 'construction-store-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChzN6W8DSLH76ngYBtHLh0ApNs83e75c4',
    appId: '1:1099117948271:android:992f26f1a20063455bcc9a',
    messagingSenderId: '1099117948271',
    projectId: 'construction-store-mobile-app',
    storageBucket: 'construction-store-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgtEP6xaGMujQxXSpi7o-Ei-LseTxSpRs',
    appId: '1:1099117948271:ios:cbd14b3c05eee6435bcc9a',
    messagingSenderId: '1099117948271',
    projectId: 'construction-store-mobile-app',
    storageBucket: 'construction-store-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.shopeCollectionApp',
  );
}
